# Generated by Django 3.1.5 on 2021-01-06 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210106_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='langauge',
            new_name='language',
        ),
    ]
